Repository apify/actor-whitepaper-web, pull requests merged in 2025-02, with the labels that each got.

#86 Text update
  src/content/pages/index.mdx
Labels: enhancement, top-priority

#88 Fixing the Notion URL
  src/content/pages/index.mdx
Labels: bug

#90 Integrate FirstPromoter tracking
  src/components/BaseHead.astro
  src/components/FirstPromoterTracker.astro
Labels: enhancement

#105 Update architecture diagrams with consistent naming and simplified labels
  src/content/pages/illu-diagram-horiz@2x.png
  src/content/pages/illu-diagram-vert@2x.png
Labels: enhancement, top-priority

#114 sync: Update MDX content from Whitepaper
  src/content/pages/index.mdx
Labels: sync

#115 sync: Update MDX content from Whitepaper
  src/content/pages/index.mdx
Labels: sync
